module.exports = {
   ROLE_USER: "role_user",
   ROLE_ADMIN: "role_admin",
   ROLE_PSYCHOLOGIST: "role_psychologist",
   SUPPORT_INFO: "Info",
   SUPPORT_PROBLEM: "Problem",
   SUPPORT_COMPLAINT: "Complaint",
   VALID_TIME_INTERVALS: {
      0:  { startTime: '10:00:00', endTime: '10:45:00' },  
      1:  { startTime: '11:00:00', endTime: '11:45:00' },  
      2:  { startTime: '12:00:00', endTime: '12:45:00' },  
      3:  { startTime: '13:00:00', endTime: '13:45:00' },  
      4:  { startTime: '14:00:00', endTime: '14:45:00' },  
      5:  { startTime: '15:00:00', endTime: '15:45:00' },  
      6:  { startTime: '16:00:00', endTime: '16:45:00' },  
      7:  { startTime: '17:00:00', endTime: '17:45:00' },  
      8:  { startTime: '18:00:00', endTime: '18:45:00' },  
      9:  { startTime: '19:00:00', endTime: '19:45:00' },  
      10: { startTime: '20:00:00', endTime: '20:45:00' },  
      11: { startTime: '21:00:00', endTime: '21:45:00' },  
      12: { startTime: '22:00:00', endTime: '22:45:00' },  
   },
   DAYS_3: 2 * 24 * 60 * 60 * 1000,
   ONE_DAY: 24 * 60 * 60 * 1000,
   psychology_topics: [
      'Abortion',
      'Addictions',
      'ADHD',
      'Aging',
      'Alzheimer',
      'Anger',
      'Anxiety',
      'Autism spectrum disorder',
      'Bipolar Disorder',
      'Bullying',
      'Children',
      'Death & Dying',
      'Depression',
      'Disability',
      'Disasters',
      'Eating Disorders',
      'Education',
      'Emotional Health',
      'Environment',
      'Ethics',
      'Hate Crimes',
      'Health Disparities',
      'HIV & AIDS',
      'Human Rights',
      'Hypnosis',
      'Immigration',
      'Intelligence',
      'Kids & the Media',
      'Law & Psychology',
      'Learning & Memory',
      'Lesbian, Gay, Bisexual, Transgender',
      'Marriage & Divorce',
      'Military',
      'Money',
      'Obesity',
      'Pain',
      'Parenting',
      'Personality',
      'Post-traumatic Stress Disorder',
      'Race',
      'Racism, bias, and discrimination',
      'Schizophrenia',
      'Sex',
      'Sexual Abuse',
      'Shyness',
      'Sleep',
      'Socioeconomic Status',
      'Sport and Exercise',
      'Stress',
      'Suicide',
      'Teens',
      'Testing Issues',
      'Therapy',
      'Trauma',
      'Violence',
      'Women & Men',
      'Workplace Issues',
   ]
}